name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href /portfolio_two/

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /portfolio_two/
          webFolder: build/web
